### ISSUE TITLE
Link from FAL TCA explanation to "inline" broken

### ISSUE THREAD

**Issue by mbrodala** [TYPO3-Documentation/TYPO3CMS-Reference-FileAbstractionLayer#23]
Currently the [FAL TCA explanation](https://docs.typo3.org/typo3cms/FileAbstractionLayerReference/UsingFal/Tca/Index.html) links to the following URL:

https://docs.typo3.org/typo3cms/TCAReference/Reference/Columns/Inline/Index.html#columns-inline

However, it should be the following instead:

https://docs.typo3.org/typo3cms/TCAReference/ColumnsConfig/Type/Inline.html

I am not sure how to update the link myself given the fact that it somehow seems to reference the URL through an internal identifier:

```rst
:ref:`inline-type field <t3tca:columns-inline>`
```

**Comment by marble** [comment]
### Fixed.
Thanks for reporting.
### How?
 The only thing I had to do is to trigger a new rendering of the FAL document.
### How does it work?

We are linking to a label ```:ref:`columns-inline` ``` (= referencing a target in an arbitrary file of the same manual). But since this belongs to a different manual, we need to prefix the name of that manual: ```:ref:`t3tca:columns-inline` ``` That name `t3tca` is the name we have given it ourselves int the Settings.cfg in the FAL manual. This is called cross-referencing with the intersphinx mechanism.

With ```:ref:`t3tca:columns-inline` ``` the linktext shown well be whatever the text of the headline is that follows the label in the TCA manual. Since we want to control the linktext ourselves in the FAL manual we can do so by writing ```this is our linktext <:ref:`t3tca:columns-inline>` ```.

### Understanding the benefits

The TCA manual has been reworked. Text and maybe urls changed, but the - purely - symbolic label has been kept. As a result the links (= intersphinx references) in foreign manuals will work again as soon they are rebuild.

### Tips

1. For convenience many manuals already have a page "Linktargets" where you can easily see what linktargets are available. Example: https://docs.typo3.org/typo3cms/TCAReference/Targets.html

2. As an editor you should not change or remove labels once they have been published. If you feel that a label (= linktarget) should be changed you should keep the old one and add the new one on a separate line. You cannont know whether some other manual in the world links to the label you would like to remove. You still CAN remove that label. The only problem that may arise is that foreign links aren't generated any more.

**Comment by mbrodala** [comment]
@marble Thanks for the detailed explanation. :-)
